### PR TITLE
Hey faggot this adds bump counts

### PR DESCRIPTION
**Pull request by theganon**
I've never written any PHP before and it's bretty shit, but here's a bump count patch.
Be sure to test it and shidddd

### CODE REVIEW

**Comment by Stavsen** [comment]
Add timestamps and it will close issue #3

**Comment by theganon** [comment]
This now also has timestamps

**Comment by yur3i** [comment]
Yeah looks good. I'll test this stuff now and provided everything works ok I'll push out the new version with all the stuff added today tonight. If not I'll work on fixing things and push it tomorrow.

**Comment by Stavsen** [comment]
Close #3

**Pull request merged**
